vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = true
vim.opt.guicursor = ""
vim.opt.mouse = "a"
vim.opt.autowrite = true
vim.opt.clipboard = "unnamedplus"
vim.opt.spelllang = { "en" }
vim.opt.smartcase = true
vim.opt.splitbelow = true
vim.opt.splitright = true
